### ISSUE TITLE
teams_scraper returns 503

### ISSUE THREAD

**Issue by prosilico** [vaastav/Fantasy-Premier-League#74]
Hello,

I have been using teams_scraper.py successfully but am now getting the following error:

```
python ./teams_scraper.py 1245518
Traceback (most recent call last):
  File "./teams_scraper.py", line 29, in <module>
    main()
  File "./teams_scraper.py", line 26, in main
    store_data(team_id, output_folder)
  File "./teams_scraper.py", line 7, in store_data
    summary = get_entry_data(team_id)
  File "C:\repos\Fantasy-Premier-League\getters.py", line 49, in get_entry_data
    raise Exception("Response was code " + str(response.status_code))
Exception: Response was code 503
```

Running on Anaconda3, Windows 10

**Comment by vaastav** [comment]
This happens when the game is updating. If you tried it when the game was updating then this is the expected behaviour.
